#import '@blocks/CardBlock/CardBlock.fragment.gql'
#import '@blocks/HeadingBlock/HeadingBlock.fragment.gql'

query Home($locale: SiteLocale!) {
    site: _site {
      favicon: faviconMetaTags {
        attributes
        content
        tag
      }
    }
    page: home(locale: $locale) {
        seo: _seoMetaTags {
            attributes
            content
            tag
        }
        title
        body {
            __typename
            ...CardBlock
            ...HeadingBlock
        }
    }
}
