#import '@blocks/CardBlock/CardBlock.fragment.gql'
#import '@blocks/HeadingBlock/HeadingBlock.fragment.gql'
#import '@blocks/SectionBlock/SectionBlock.fragment.gql'

query Page($locale: SiteLocale!) {
    _site {
      favicon: faviconMetaTags {
        attributes
        content
        tag
      }
    }
    page(locale: $locale) {
        seo: _seoMetaTags {
            attributes
            content
            tag
        }
        title
        slug
        body {
            __typename
            ...CardBlock
            ...HeadingBlock
            ...SectionBlock
        }
    }
}
